### ISSUE TITLE
Version requirements

### ISSUE THREAD

**Issue by kwolf** [evenup/evenup-backup#53]
Is the reason you're requiring latest RH and Ubuntu due to the ruby 1.9.3 requirement? If that's it, would you accept a PR that requires Ruby 1.9.3 instead?  I'm going to have to fork it because we have Ubuntu 12.04 & CentOS 5 and 6 systems I need to use a similar module on.

**Comment by jlambert121** [comment]
The backup 4 gem requires 1.9.3, yeah.  I'm open to a PR to allow this on other systems - I just tested it on the ones I use (CentOS7) and were easy (Ubuntu 14.04).
