### ISSUE TITLE
dependency not met in ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by betavisionsys** [evenup/evenup-backup#68]
hi i'm trying to install it on ubuntu but the module asks for rubygem-backup when i try to run the puppet agent --test

Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install rubygem-backup' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package rubygem-backup
Error: /Stage[main]/Backups/Package[rubygem-backup]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install rubygem-backup' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package rubygem-backup
Notice: /Stage[main]/Backups/File[/var/log/backup]: Dependency Package[rubygem-backup] has failures: true
Warning: /Stage[main]/Backups/File[/var/log/backup]: Skipping because of failed dependencies
Notice: /Stage[main]/Backups/File[/etc/backup]: Dependency Package[rubygem-backup] has failures: true
Warning: /Stage[main]/Backups/File[/etc/backup]: Skipping because of failed dependencies
Notice: /Stage[main]/Backups/File[/etc/backup/config.rb]: Dependency Package[rubygem-backup] has failures: true
Warning: /Stage[main]/Backups/File[/etc/backup/config.rb]: Skipping because of failed dependencies
Notice: /Stage[main]/Backups/File[/etc/backup/models]: Dependency Package[rubygem-backup] has failures: true
Warning: /Stage[main]/Backups/File[/etc/backup/models]: Skipping because of failed dependencies

how can i solve this?

**Comment by jlambert121** [comment]
This module expects you to have a package rather than use the native gem.  It mentions it in the readme, but maybe should be more obvious.  There's a script there that makes a RPM with fpm, but it should easily adapt to debs because FPM is awesome.
